name: sourceMapDome
on:
  push:
    branches:
      - main
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
       # 拉取代码
      - uses: actions/checkout@v2
      # 下载Node
      - uses: pnpm/actions-setup@v3
        with:
          node-version: "24.x"
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_SECRET }}
          BRANCH: gh-pages
          publish_dir: ./dist
