name: todolist 自动部署
on:
  bush:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Checkout
      - uses: actions/checkout@v3

      - name: Instail and Build
        run:
         npm install
         npm run build
      - name: Deploy
        uses: peaceiris/actions-main@v3
        with:
          github_token: ${{ secrets.DEPLOY_SECRET }}
          BRANCH: main
          publish_dir: ./dist
